#include "s_gpio_init.h"


#if SERVO_MCU != NO_MCU
void port_init(void)
{
    HPM_IOC->PAD[IOC_PAD_PC19].FUNC_CTL = IOC_PC19_FUNC_CTL_GPIO_C_19; 
    //HPM_IOC->PAD[IOC_PAD_PC18].FUNC_CTL = IOC_PC18_FUNC_CTL_GPIO_C_18; 
    HPM_GPIO0->OE[GPIO_DI_GPIOC].SET = 1 << 19;
    //HPM_GPIO0->OE[GPIO_DI_GPIOC].SET = 1 << 18;

    //PWM ON
    HPM_GPIO0->DO[GPIO_DI_GPIOC].SET = 1 << 23;
    HPM_IOC->PAD[IOC_PAD_PC23].FUNC_CTL = IOC_PC23_FUNC_CTL_GPIO_C_23; 
    HPM_GPIO0->OE[GPIO_DI_GPIOC].SET = 1 << 23;
    HPM_GPIO0->DO[GPIO_DI_GPIOC].CLEAR = 1 << 23;

    //BRAKE
    HPM_GPIO0->DO[GPIO_DI_GPIOC].SET = 1 << 22;
    HPM_IOC->PAD[IOC_PAD_PC23].FUNC_CTL = IOC_PC22_FUNC_CTL_GPIO_C_22; 
    HPM_GPIO0->OE[GPIO_DI_GPIOC].SET = 1 << 22;
    HPM_GPIO0->DO[GPIO_DI_GPIOC].CLEAR = 1 << 22;
}
#else


#endif
