/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.2.3-0-gc1071ab+c1071ab3197f9bbf718123ec5bbabf449b2f7bab

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: DS301_profile.xpd
        File Version: 1

        Created:      2020/11/23 19:00:00
        Created By:   
        Modified:     2026/5/5 16:03:23
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: New Product
        Product ID:   

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H

#include "CO_ODinterface.h"
#include "board.h"
#include "SV_DataType.h"

/** 
UINT8: Should be adapted to the unsigned8 type of the microcontroller  */
#ifndef UINT8
#define UINT8                                     uint8_t
#endif

/** 
UINT16: Should be adapted to the unsigned16 type of the microcontroller  */
#ifndef UINT16
#define UINT16                                    uint16_t
#endif

/** 
UINT32: Should be adapted to the unsigned32 type of the microcontroller  */
#ifndef UINT32
#define UINT32                                    uint32_t
#endif

/** 
UINT64: Should be adapted to the unsigned64 type of the microcontroller  */
#ifndef UINT64
#define UINT64                                    uint64_t
#endif

/** 
USHORT: Should be adapted to the unsigned16 type of the microcontroller */
#ifndef USHORT
#define USHORT                                    uint16_t
#endif

/** 
INT8: Should be adapted to the integer8 type of the microcontroller */
#ifndef INT8
#define INT8                                      int8_t
#endif

/** 
INT16: Should be adapted to the integer16 type of the microcontroller  */
#ifndef INT16
#define INT16                                     int16_t
#endif

/** 
INT32: Should be adapted to the integer32 type of the microcontroller */
#ifndef INT32
#define INT32                                     int32_t
#endif

/** 
INT64: Should be adapted to the integer64 type of the microcontroller */
#ifndef INT64
#define INT64                                     int64_t
#endif

/** 
CHAR: Should be adapted to the character type of the microcontroller */
#ifndef CHAR
#define CHAR                                      char
#endif

/** 
UCHAR: Should be adapted to the unsigned character type of the microcontroller */
#ifndef UCHAR
#define UCHAR                                     unsigned char
#endif

/** 
BOOL: Should be adapted to the boolean type of the microcontroller */
#ifndef BOOL
#define BOOL                                      uint8_t
#endif


#define PDOMAXINDEX  8

/** 
OBJ_STRUCT_PACKED_START: Is defined before the typedef struct construct to pack the OBJECT structures if necessary */
#ifndef OBJ_STRUCT_PACKED_START
#define OBJ_STRUCT_PACKED_START 
#endif

/** 
OBJ_STRUCT_PACKED_END: Is defined after the typedef struct {} construct to pack the OBJECT structures if necessary */
#ifndef OBJ_STRUCT_PACKED_END
#define OBJ_STRUCT_PACKED_END 
#endif

/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_SYNC 1
#define OD_CNT_SYNC_PROD 1
#define OD_CNT_STORAGE 1
#define OD_CNT_TIME 1
#define OD_CNT_EM_PROD 1
#define OD_CNT_HB_CONS 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1
#define OD_CNT_SDO_CLI 1
#define OD_CNT_RPDO 4
#define OD_CNT_TPDO 4


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/
#define OD_CNT_ARR_1003 16
#define OD_CNT_ARR_1010 4
#define OD_CNT_ARR_1011 4
#define OD_CNT_ARR_1016 8
#define OD_CNT_ARR_2107 1
#define OD_CNT_ARR_2108 1
#define OD_CNT_ARR_2109 1
#define OD_CNT_ARR_210A 1
#define OD_CNT_ARR_210B 1
#define OD_CNT_ARR_210C 1


#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1002 &OD->list[2]
#define OD_ENTRY_H1003 &OD->list[3]
#define OD_ENTRY_H1005 &OD->list[4]
#define OD_ENTRY_H1006 &OD->list[5]
#define OD_ENTRY_H1007 &OD->list[6]
#define OD_ENTRY_H1008 &OD->list[7]
#define OD_ENTRY_H1009 &OD->list[8]
#define OD_ENTRY_H100A &OD->list[9]
#define OD_ENTRY_H100C &OD->list[10]
#define OD_ENTRY_H100D &OD->list[11]
#define OD_ENTRY_H1010 &OD->list[12]
#define OD_ENTRY_H1011 &OD->list[13]
#define OD_ENTRY_H1012 &OD->list[14]
#define OD_ENTRY_H1014 &OD->list[15]
#define OD_ENTRY_H1015 &OD->list[16]
#define OD_ENTRY_H1016 &OD->list[17]
#define OD_ENTRY_H1017 &OD->list[18]
#define OD_ENTRY_H1018 &OD->list[19]
#define OD_ENTRY_H1019 &OD->list[20]
#define OD_ENTRY_H1200 &OD->list[21]
#define OD_ENTRY_H1280 &OD->list[22]
#define OD_ENTRY_H1400 &OD->list[23]
#define OD_ENTRY_H1401 &OD->list[24]
#define OD_ENTRY_H1402 &OD->list[25]
#define OD_ENTRY_H1403 &OD->list[26]
#define OD_ENTRY_H1600 &OD->list[27]
#define OD_ENTRY_H1601 &OD->list[28]
#define OD_ENTRY_H1602 &OD->list[29]
#define OD_ENTRY_H1603 &OD->list[30]
#define OD_ENTRY_H1800 &OD->list[31]
#define OD_ENTRY_H1801 &OD->list[32]
#define OD_ENTRY_H1802 &OD->list[33]
#define OD_ENTRY_H1803 &OD->list[34]
#define OD_ENTRY_H1A00 &OD->list[35]
#define OD_ENTRY_H1A01 &OD->list[36]
#define OD_ENTRY_H1A02 &OD->list[37]
#define OD_ENTRY_H1A03 &OD->list[38]



/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType                       &OD->list[0]
#define OD_ENTRY_H1001_errorRegister                    &OD->list[1]
#define OD_ENTRY_H1002_facturerStatusRegister           &OD->list[2]
#define OD_ENTRY_H1003_pre_definedErrorField            &OD->list[3]
#define OD_ENTRY_H1005_COB_ID_SYNCMessage               &OD->list[4]
#define OD_ENTRY_H1006_communicationCyclePeriod         &OD->list[5]
#define OD_ENTRY_H1007_synchronousWindowLength          &OD->list[6]
#define OD_ENTRY_H1008_manufacturerDeviceName           &OD->list[7]
#define OD_ENTRY_H1009_manufacturerHardwareVersion      &OD->list[8]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion      &OD->list[9]
#define OD_ENTRY_H100C_guardTime                        &OD->list[10]
#define OD_ENTRY_H100D_lifeTimeFactor                   &OD->list[11]
#define OD_ENTRY_H1010_storeParameters                  &OD->list[12]
#define OD_ENTRY_H1011_restoreDefaultParameters         &OD->list[13]
#define OD_ENTRY_H1012_COB_IDTimeStampObject            &OD->list[14]
#define OD_ENTRY_H1014_COB_ID_EMCY                      &OD->list[15]
#define OD_ENTRY_H1015_inhibitTimeEMCY                  &OD->list[16]
#define OD_ENTRY_H1016_consumerHeartbeatTime            &OD->list[17]
#define OD_ENTRY_H1017_producerHeartbeatTime            &OD->list[18]
#define OD_ENTRY_H1018_identity                         &OD->list[19]
#define OD_ENTRY_H1019_synchronousCounterOverflowValue  &OD->list[20]
#define OD_ENTRY_H1200_SDOServerParameter               &OD->list[21]
#define OD_ENTRY_H1280_SDOClientParameter               &OD->list[22]
#define OD_ENTRY_H1400_RPDOCommunicationParameter       &OD->list[23]
#define OD_ENTRY_H1401_RPDOCommunicationParameter       &OD->list[24]
#define OD_ENTRY_H1402_RPDOCommunicationParameter       &OD->list[25]
#define OD_ENTRY_H1403_RPDOCommunicationParameter       &OD->list[26]
#define OD_ENTRY_H1600_RPDOMappingParameter             &OD->list[27]
#define OD_ENTRY_H1601_RPDOMappingParameter             &OD->list[28]
#define OD_ENTRY_H1602_RPDOMappingParameter             &OD->list[29]
#define OD_ENTRY_H1603_RPDOMappingParameter             &OD->list[30]
#define OD_ENTRY_H1800_TPDOCommunicationParameter       &OD->list[31]
#define OD_ENTRY_H1801_TPDOCommunicationParameter       &OD->list[32]
#define OD_ENTRY_H1802_TPDOCommunicationParameter       &OD->list[33]
#define OD_ENTRY_H1803_TPDOCommunicationParameter       &OD->list[34]
#define OD_ENTRY_H1A00_TPDOMappingParameter             &OD->list[35]
#define OD_ENTRY_H1A01_TPDOMappingParameter             &OD->list[36]
#define OD_ENTRY_H1A02_TPDOMappingParameter             &OD->list[37]
#define OD_ENTRY_H1A03_TPDOMappingParameter             &OD->list[38]




/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = OD_CNT_HB_CONS;\
    (config).CNT_ARR_1016 = OD_CNT_ARR_1016;\
    (config).ENTRY_H1016 = OD_ENTRY_H1016;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = OD_ENTRY_H1014;\
    (config).ENTRY_H1015 = OD_ENTRY_H1015;\
    (config).CNT_ARR_1003 = OD_CNT_ARR_1003;\
    (config).ENTRY_H1003 = OD_ENTRY_H1003;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = OD_CNT_SDO_CLI;\
    (config).ENTRY_H1280 = OD_ENTRY_H1280;\
    (config).CNT_TIME = OD_CNT_TIME;\
    (config).ENTRY_H1012 = OD_ENTRY_H1012;\
    (config).CNT_SYNC = OD_CNT_SYNC;\
    (config).ENTRY_H1005 = OD_ENTRY_H1005;\
    (config).ENTRY_H1006 = OD_ENTRY_H1006;\
    (config).ENTRY_H1007 = OD_ENTRY_H1007;\
    (config).ENTRY_H1019 = OD_ENTRY_H1019;\
    (config).CNT_RPDO = OD_CNT_RPDO;\
    (config).ENTRY_H1400 = OD_ENTRY_H1400;\
    (config).ENTRY_H1600 = OD_ENTRY_H1600;\
    (config).CNT_TPDO = OD_CNT_TPDO;\
    (config).ENTRY_H1800 = OD_ENTRY_H1800;\
    (config).ENTRY_H1A00 = OD_ENTRY_H1A00;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

/////////////////////////////////////////////////////////////

/** \brief 0x607D (Software Position Limit) data structure*/
typedef struct  {
   UINT16    u16SubIndex0; /**< \brief SubIndex 0 use 1 byte */
   INT32    i32MinLimit; /**< \brief Minimum limit*/
   INT32    i32MaxLimit; /**< \brief Maximum limit*/
}
TOBJ607D;

/** \brief 0x6099 (Homing Speeds) data structure*/
typedef struct  {
   UINT16     u16SubIndex0; /**< \brief SubIndex 0 use 1 byte*/
   UINT32    i32Speedforswitch; /**< \brief Speed during search for switch*/
   UINT32    i32Speedforzero;
}
TOBJ6099;

/** \brief 0x6091 (Gear ratio) data structure*/
typedef struct  {
   UINT16   u16SubIndex0; /**< \brief SubIndex 0 use 1 byte*/
   UINT32    MotorRevolutions;
   UINT32    ShaftRevolutions;
}
TOBJ6091;

/** \brief Object 0x60C1 (Interpolation Data Record) data structure*/
typedef struct  {
   UINT16   u16SubIndex0; /**< \brief SubIndex 0 use 1 byte*/
   INT32   u32Interpolationdatarecord; /**< \brief Interpolation data record*/
}
TOBJ60C1;
/** \brief Object 0x60C2 (Interpolation Time Period) data structure*/
typedef struct  {
   UINT16   u16SubIndex0; /**< \brief SubIndex 0 use 1 byte */
   UINT8    u8InterpolationPeriod; /**< \brief Interpolation period*/
   INT8     i8InterpolationIndex; /**< \brief Interpolation index*/
}
TOBJ60C2;

/** \brief Data structure to handle the axis specific object data*/
typedef struct
{
    UINT16   objErrorCode;              /**< \brief Error Code (0x603F)*/
    UINT16   objControlWord;            /**< \brief Control Word (0x6040)*/
    UINT16   objStatusWord;             /**< \brief Status Word (0x6041)*/
    INT16    objQuickStopOptionCode;    /**< \brief Quick Stop Option Code (0x605A)*/
    
    INT16    objShutdownOptionCode;     /**< \brief Shutdown Option Code (0x605B)*/
    INT16    objDisableOptionCode;      /**< \brief Disable operation option code (0x605C)*/
    INT16    objHaltOptionCode;         /**< \brief Halt Option Code (0x605D)*/
    INT16    objFaultOptionCode;        /**< \brief Fault Option Code (0x605E)*/
    
    INT16    rsd605F_1;
    INT16    rsd605F_2;
    INT8     objModesOfOperation;               /**< \brief Modes of Operation (0x6060)*/
    INT8     rsd1; 
    INT8     objModesOfOperationDisplay;        /**< \brief Mode of Operation Display (0x6061)*/
    INT8     rsd2;
    
    INT32    objPositionDemandValue;            /**breaf Position Demand Walue(0x6062)*/
    INT32    objPositionActualInterValue;       /**breaf Position Actual Internal Value(0x6063)*/
    INT32    objPositionActualValue;            /**< \brief Position Actual Value (0x6064)*/
    UINT32   objFollowingErrorWindow;           /**breaf Following Error Window(0x6065)*/
    
    UINT16   objFollowErrorTimeOut;             /**breaf Follow Error Time Out(0x6066)*/
    UINT16   rsd3;
    UINT32   objPositionWindow;                 /**breaf Position Window(0x6067)*/
    
    UINT16   objPositionWindowTime;             /**breaf Position Window Time(0x6068)*/
    UINT16   rsd4;
    UINT16   rsd6069_1;
    UINT16   rsd6069_2;
    
    INT32    objVelocityDemandValue;            /**breaf Velocity Demand Value(0x606B)*/
    INT32    objVelocityActualValue;            /**< \brief Actual Velocity Value (0x606C)*/
    
    UINT16   objVelocityWindow;                 /**brief Velocity Window(0x606D)*/
    UINT16   objVelocityWindowTime;             /**brief Velocity Window Time(0x606E)*/
    UINT16   objVelocitythreshold;              /**brief Velocity threshold(0x606F)*/
    UINT16   objVelocitythresholdTime;          /**brief Velocity threshold time(0x6070)*/   //
    
    INT16    objTargetTorque;                   /**brief Target Torque(0x6071)*/
    UINT16   objMaxTorque;                      /**brief Max Torque(0x6072)*/
    UINT16   rsd6073_1;      
    UINT16   rsd6073_2;      
    
    INT16    objTorqueDemandValue;              /**brief torque Demand Value(0x6074)*/
    UINT16   rsd5;
    UINT32   objMotorRatedCurrent;              /**brief Motor Rated Current(0x6075)*/        //
    
    UINT32   objMotorRatedTorque;               /**brief Motor Rated Torque(0x6076)*/          //
    INT16    objTorqueActualValue;              /**< \brief Torque Actual Value (0x6077)*/
    INT16    objCurrentActualValue;             /**< \brief Current Actual Value (0x6078)*/
    
    UINT32   objDCLinkActualValue;              /**< \brief DC Link Circuit Value (0x6079)*/
    INT32    objTargetPosition;                 /**< \brief Target Position (0x607A)*/
    
    UINT16   rsd607B_1;
    UINT16   rsd607B_2;
    INT32    objHomeOffset;                     /**brief Home Offset(0x607C)*/
    
    TOBJ607D objSoftwarePositionLimit;          /**< \brief Software Position limit (0x607D)*/
    UINT16   rsd6;
    UINT16   objPolarity;                       /**brief Polarity(0x607E)*/
    
    UINT32   objMaxProfileVelocity;             /**brief Max Profile Velocity(0x607F)*/
    UINT32   objMaxMotorSpeed;                  /**brief Max Motor Speed(0x6080)*/
    UINT32   objProfileVelocity;                /**brief Profile Velocity(0x6081)*/
    UINT16   rsd6082_1;
    UINT16   rsd6082_2;
    
    UINT32   objProfileAcceleration;            /**brief Profile Acceleration(0x6083)*/
    UINT32   objProfileDeceleration;            /**brief Profile Deceleration(0x6084)*/
    UINT32   objQuickStopDeclaration;           /**< \brief Quick Stop Declaration (0x6085)*/
    UINT16   rsd6086_1;
    UINT16   rsd6086_2;
    
    UINT32   objTorqueSlop;                     /**brief Torque Slop(0x6087)*/
    TOBJ6091 objGearRatio;                      /**brief Gear Ratio (0x6091)*/
    
    INT8     objHomeMethod;                     /**brief Home Method(0x6098)*/
    UINT8    rsd7;
    UINT8    rsd8;
    UINT8    rsd9;
    TOBJ6099 objHomingSpeeds;                   /*brief Homing Speeds(0x6099)*/
    UINT32   objHomingAcceleration;             /**brief Homing Acceleration(0x609A)*/
    
    UINT16   rsd609B_1;
    UINT16   rsd609B_2;
    UINT16   rsd609C_1;
    UINT16   rsd609C_2;
    
    INT32    objPositionoffset;                 /**brief Position Offset(0x60B0)*/
    INT32    objVelocityOffset;                 /**brief Velocity Offset(0x60B1)*/
    INT16    objTorqueOffset;                   /**brief Torque Offset(0x60B2)*/
    UINT16   rsd10;

    UINT16   objTouchProbeFunction;             /**brief Touch Probe Function(0x60B8)*/
    UINT16   objTouchProbeStatus;               /**brief Touch Probe Status(0x60B9)*/
    INT32    objTP1PositiveEPValue;             /**brief Touch Probe 1 Positive Edge Position Value(0x60BA)*/
    INT32    objTP1NegativeEPValue;             /**brief Touch Probe 1 Negative Edge Position Value(0x60BB)*/
    INT32    objTP2PositiveEPValue;             /**brief Touch Probe 1 Positive Edge Position Value(0x60BC)*/
    INT32    objTP2NegativeEPValue;             /**brief Touch Probe 1 Negative Edge Position Value(0x60BD)*/

    TOBJ60C1 objInterpolationDataRecord;        /**brief Interpolation Data Record(0x60C1)*/
    TOBJ60C2 objInterpolationTimePeriod;        /**< \brief Interpolation Time Period (0x60C2)*/
    UINT32   objMaxAcceleration;                /**brief Max acceleration(0x60C5)*/
    UINT32   ojbMaxDeceleration;                /**brief Max deceleration(0x60C6)*/
    
    UINT16   objPosTqLimitValue;                /**brief Positive Torque Limit Value(0x60E0)*/
    UINT16   objNegTqLimitValue;                /**brief Negative Torque Limit Value(0x60E1)*/
    INT32    objFollowingErrorActualValue;      /**brief Following Error Actual Value(0x60F4)*/
    INT32    objPositionDemandInterValue;       /**brief Position Demand Internal Value(0x60FC)*/
    UINT32   objDigitalInputs;                  /**brief Digital Inputs(0x60FD)*/
    UINT32   objDigitalOutput;                  /**brief Digital Output(0x60FE)*/
    INT32    objTargetVelocity;                 /**< \brief Target Velocity (0x60FF)*/
    UINT32   objSupportedDriveModes;            /**< \brief Supported Drive Modes (0x6502)*/
}
CiA402Objects;

/** \brief Data structure to handle an Cia402 axis*/
typedef struct
{
    BOOL        bAxisIsActive;          /**< \brief Indicates if active is active*/
    BOOL        bAxisInitReady;         //驱动器初始化完成
    BOOL        bAxisFunctionEnabled;   //使能驱动器
    BOOL        rsd1;
    UINT16      i16State;               /**< \brief Axis state*/
    UINT16      CmdSource;              //表示的是当前控制命令的来源，0表示内部命令，1表示外部命令，用于标注状态字Remote位。
    UINT16      u16PendingOptionCode;   /**< \brief Pending operation code*/
    UINT16      u16PendState;           /**< \brief Pending*/
    UINT16      EcatStopMode;           //停止方式
    UINT16      EcatDbFlag;             //动态制动标志
    UINT16      OffStop_FaultStop;      //ECAT伺服中故障时的停车方式
    UINT16      OffStop_QuickStop;      //ECAT伺服中Qick Stop停机方式
    UINT16      OffStop_HaltStop;       //ECAT伺服中Halt停机方式:等于1表示慢速停车，为2表示快速停车
    UINT16      OffStop_Other;           //其他模块发出的停车方式
    UINT16      LastControlWord6040;    //上次操作的控制字
    UINT16      LastFaultRest;
    UINT16      StatusWord;
    UINT16      InitReady;              //准备好
    double      Encoderres;             //编码器分辨率
    double      SpdAccDecPu;            /**< \brief Current position within control loop*/
    double      PosAccDecPu;            /**< \brief Current position within control loop*/
    double      SpdCmdPU;               //速度给定标幺值
    double      SpdFbPu; 
    double      PosPU;                  //位置环标幺值
    float          TorquePU;            //
    UINT16     TpN;                     //在中断时间内要执行多少次位置环更新     DrvCoeff->Tpwm;
    UINT16     TprwTimes;               //当前已经执行了多少次；
    UINT32     u32CycleTime;            /**< \brief Motion controller cycletime in us*/
    INT32       objTargetLastPosition;
    UINT32     LocationTarget_limit;
    CiA402Objects        Objects;       /**< \brief CiA402 Axis object variable*/
}TCiA402Axis;



typedef struct OBJ_STRUCT_PACKED_START {
    UINT16   u16SubIndex0; /**< \brief SubIndex 0 use 1 byte*/
    UINT32   rsd[8]; /**< \brief EtherCAT vendor ID */
} OBJ_STRUCT_PACKED_END
TOBJ1003;

/*---------------------------------------------
-    0x1018
-----------------------------------------------*/
/**
* \brief 0x1018 (Identity) object structure
*/
typedef struct OBJ_STRUCT_PACKED_START {
    UINT16   u16SubIndex0; /**< \brief SubIndex 0 use 1 byte*/
    UINT32   u32VendorID; /**< \brief EtherCAT vendor ID */
    UINT32   u32Productcode; /**< \brief Product code*/
    UINT32   u32Revision; /**< \brief Revision number*/
    UINT32   u32Serialnumber; /**< \brief Serial number*/
} OBJ_STRUCT_PACKED_END
TOBJ1018;

/*---------------------------------------------
-    0x16XX
-----------------------------------------------*/
/** \brief 0x16XX data structure*/
typedef struct  {
   UINT16   u16SubIndex0; /**< \brief SubIndex 0  use 1 byte  */
   UINT32   aEntries[PDOMAXINDEX];
//   UINT16   *pObjectData[PDOMAXINDEX];
//   UINT16   BitLength[PDOMAXINDEX];
}
TOBJ16XX;

/*---------------------------------------------
-    0x1AXX
-----------------------------------------------*/
/** \brief 0x1AXX data structure*/
typedef struct  {
   UINT16   u16SubIndex0; /**< \brief SubIndex 0  use 1 byte  */
   UINT32   aEntries[PDOMAXINDEX];//   ڴ洢
//   UINT16   *pObjectData[PDOMAXINDEX];
//   UINT16   BitLength[PDOMAXINDEX];
}
TOBJ1AXX;

typedef struct  {
   UINT16   IndexNum;   /**< \brief SubIndex 0*/
   UINT16   *pObjectData[((PDOMAXINDEX << 2) + 2)];
   UINT16   BitLength[((PDOMAXINDEX << 2) + 2)];
}
TOBJPDOBUFF;

typedef struct {
    UINT16 highestSub_indexSupported;
    UINT32 COB_IDClientToServerRx;
    UINT32 COB_IDServerToClientTx;
} TOBJ1200;

typedef struct {
    UINT16 highestSub_indexSupported;
    UINT32 COB_IDClientToServerTx;
    UINT32 COB_IDServerToClientRx;
    UINT16 node_IDOfTheSDOServer;
} TOBJ1280;

typedef struct {
    UINT16 highestSub_indexSupported;
    UINT32 COB_IDUsedByRPDO;
    UINT16 transmissionType;
    UINT16 eventTimer;
} TOBJ14xx;

typedef struct {
    UINT16 highestSub_indexSupported;
    UINT32 COB_IDUsedByTPDO;
    UINT16 transmissionType;
    UINT16 inhibitTime;
    UINT16 eventTimer;
    UINT16 SYNCStartValue;
} TOBJ18xx;

typedef struct
{
    UINT32 u32Devicetype;            /**< \brief 0x1000 (Device type)*/
    UINT16 u16ErrorRegister;         /**< \brief 0x1001 (Error Register) use 1 byte  */
    UINT32 x1002_FacturerStatusRegister;/**< \brief 0x1002 ()*/
    TOBJ1003 rsd;    

    UINT16 IIC_CheckStart;
    UINT16 rsd1;                              // 485 addr 0x1000  
    UINT32 x1005_COB_ID_SYNCMessage;          /**< \brief 0x1005 () SYNC COB_ID */  //---------------
    UINT32 x1006_communicationCyclePeriod;    /**< \brief 0x1006 () 同步周期时间 us */
    UINT32 x1007_synchronousWindowLength;     /**< \brief 0x1007 () 同步窗长度 */
                                                        
    UINT32 x1012_COB_IDTimeStampObject;     /**< \brief 0x1012 () 时间戳 COB_ID  */    //---------------     
    UINT32 x1014_COB_ID_EMCY;               /**< \brief 0x1014 () EMCY COB_ID */    //--------------- 
    UINT16 x1015_inhibitTimeEMCY;           /**< \brief 0x1015 () EMCY抑制时间 */
    UINT16 x1017_producerHeartbeatTime;     /**< \brief 0x1017 () 生产者心跳包时间 */
                                    
    TOBJ1018 sIdentity;                  /**< \brief 0x1018 设备标识 */

    UINT16 x1019_synchronousCounterOverflowValue;/**< \brief 0x1019 () 同步计数器溢出值 */
    UINT16 rsd2;

    TOBJ1200 x1200_SDOServerParameter;   /**< \brief 0x1200 () SDO COB_ID*/        //--------------- 
    //TOBJ1280 x1280_SDOClientParameter;   /**< \brief 0x1280 ()*/
                                     
    TOBJ14xx x1400_RPDOCommunicationParameter;   /**< \brief 0x1400 ()*/
    TOBJ14xx x1401_RPDOCommunicationParameter;   /**< \brief 0x1401 ()*/
    TOBJ14xx x1402_RPDOCommunicationParameter;   /**< \brief 0x1402 ()*/
    TOBJ14xx x1403_RPDOCommunicationParameter;   /**< \brief 0x1403 ()*/

    TOBJ16XX sRxPDOMap0;          /**< \brief RxPDO (0x1600)*/
    TOBJ16XX sRxPDOMap1;          /**< \brief RxPDO (0x1601)*/
    TOBJ16XX sRxPDOMap2;          /**< \brief RxPDO (0x1602)*/
    TOBJ16XX sRxPDOMap3;          /**< \brief RxPDO (0x1603)*/

    TOBJ18xx x1800_TPDOCommunicationParameter;   /**< \brief 0x1800 ()*/
    TOBJ18xx x1801_TPDOCommunicationParameter;   /**< \brief 0x1801 ()*/
    TOBJ18xx x1802_TPDOCommunicationParameter;   /**< \brief 0x1802 ()*/
    TOBJ18xx x1803_TPDOCommunicationParameter;   /**< \brief 0x1803 ()*/    

    TOBJ1AXX sTxPDOMap0;          /**< \brief TxPDO (0x1A00)*/
    TOBJ1AXX sTxPDOMap1;          /**< \brief TxPDO (0x1A01)*/
    TOBJ1AXX sTxPDOMap2;          /**< \brief TxPDO (0x1A02)*/
    TOBJ1AXX sTxPDOMap3;          /**< \brief TxPDO (0x1A03)*/
    UINT16 IIC_CheckEnd;

    CHAR acDevicename[6];           /**< \brief 0x1008*/
    CHAR acHardwareversion[6];   /**< \brief 0x1009 (Hardware version) variable to handle the object data*/
    CHAR acSoftwareversion[12];   /**< \brief 0x100A*/

    UINT16 x1010_storeParameters_sub0;              /**< \brief 0x1010 ()*/
    UINT32 x1010_storeParameters[OD_CNT_ARR_1010];
    UINT16 x1011_restoreDefaultParameters_sub0;     /**< \brief 0x1011 ()*/
    UINT32 x1011_restoreDefaultParameters[OD_CNT_ARR_1011];

    //以下对象适配益优eds文件
    UINT16 x100C_guardTime;             /**< \brief 0x100C ()*/
    CHAR   x100D_lifeTimeFactor;        /**< \brief 0x100D ()*/

    UINT16 x1016_consumerHeartbeatTime_sub0;/**< \brief 0x1016 ()*/
    UINT32 x1016_consumerHeartbeatTime[OD_CNT_ARR_1016];
    /*************************************************************/
}
CommunicationObjects;


typedef struct
{
    uint16_t index;
    uint8_t subEntriesCount;
    uint8_t odObjectType; 
    OD_obj_var_t Myobj;
    OD_extension_t* extension;
} Myobj_t;//20Byte

typedef struct 
{
    uint16_t size;    
    CO_PROGMEM Myobj_t* list; 
} OD_Sub_t;

#ifndef OD_ATTR_PERSIST_COMM
#define OD_ATTR_PERSIST_COMM
#endif

extern CommunicationObjects CumObj;
extern CommunicationObjects const DefCommuObjectsValues;
extern CiA402Objects const DefCiA402ObjectValuesFull;
extern TCiA402Axis           LocalAxes;
extern CiA402Objects const DefCiA402ObjectValues;

uint8_t CO_init_OD(void);

#endif /* OD_H */
